// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace TwinCAT.ProductivityTools
{
    internal sealed partial class Vsix
    {
        public const string Id = "1e6f317c-4b46-4f08-96dc-4ab7dc8a1032";
        public const string Name = "TwinCAT 3.1 ProductivityTools";
        public const string Description = "";
        public const string Language = "en-US";
        public const string Version = "1.2.0";
        public const string Author = "Philipp Leidig";
        public const string Tags = "beckhoff twincat";
    }
}
