// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace TwinCAT.ProductivityTools
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string ProductivityToolsCmdSetString = "7e8a71c6-214a-40a2-a302-026e804258d4";
        public static Guid ProductivityToolsCmdSet = new Guid(ProductivityToolsCmdSetString);

        public const string TwinCATXaeProjectCmdSetString = "40ee08e0-8fb4-46e9-baab-100e60019b7b";
        public static Guid TwinCATXaeProjectCmdSet = new Guid(TwinCATXaeProjectCmdSetString);

        public const string TwinCATPlcProjectCmdSetString = "3b11520b-7e70-4008-a6cf-b60ae84e12b1";
        public static Guid TwinCATPlcProjectCmdSet = new Guid(TwinCATPlcProjectCmdSetString);

        public const string CommandImagesString = "5a8761e2-47d4-4be3-abd9-ce2305ef1371";
        public static Guid CommandImages = new Guid(CommandImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int TwinCATProductivityTools = 0x1020;
        public const int ProductivityToolsSubmenuGroup = 0x1200;
        public const int ProductivityToolsCommandsGroup = 0x1201;
        public const int ProductivityToolsSubmenu = 0x1202;
        public const int ShutdownCommandId = 0x0100;
        public const int RestartCommandId = 0x0101;
        public const int DeviceInfoCommandId = 0x0102;
        public const int RemoteDesktopCommandId = 0x0103;
        public const int RteInstallCommandId = 0x0104;
        public const int SetTickCommandId = 0x0105;
        public const int Toolbar = 0x1000;
        public const int ToolbarGroup = 0x1050;
        public const int RemoveCommentsCommandId = 0x0110;
        public const int RemoveRegionsCommandId = 0x0120;
        public const int TwinCATPlcFileContextMenuGroup = 0x1250;
        public const int OpenInVsCodeCommandId = 0x0210;
        public const int OpenInFileExplorerCommandId = 0x0220;
        public const int TwinCATPlcFolderContextMenuGroup = 0x2250;
        public const int EnableAdsServerCommandId = 0x0320;
        public const int TwinCATIODeviceContextMenuGroup = 0x3250;
        public const int FreezeProjectCommandId = 0x0321;
        public const int OpenLoggedEventsCommandId = 0x0322;
        public const int UseRelativeNetIdsCommandId = 0x0323;
        public const int TwinCATXaeProjectContextMenuGroup = 0x2350;
        public const int GenerateCamTablePlcCodeCommandId = 0x0422;
        public const int TwinCATNcCamTablesContextMenuGroup = 0x2450;
        public const int TwinCATXaeProjectContextMenuId = 0x8028;
        public const int TwinCATIODeviceContextMenuId = 0x8004;
        public const int TwinCATNcCamTablesContextMenuId = 0x8025;
        public const int TwinCATPlcProjectContextMenuId = 0x9013;
        public const int TwinCATPlcFileContextMenuId = 0x9011;
        public const int TwinCATPlcFolderContextMenuId = 0x9010;
        public const int TwinCatPlcCodeEditorContextMenuId = 0x9017;
        public const int ShutdownMoniker = 0x0001;
        public const int RestartMoniker = 0x0002;
        public const int DeviceInfoMoniker = 0x0003;
        public const int DownloadMoniker = 0x0004;
        public const int RemoteDesktopMoniker = 0x0005;
        public const int SpareMoniker = 0x0006;
    }
}